language: node_js
node_js: '8'
jobs:
    include:
        install: npm i
        stage: Create Env 
        command: mkdir .test ; mkdir ./.test/react ; mv * ./.test/react/ ; mv .test test
        stage: Create Config
        command: > 
              echo ''{\"clientId\": \"${CLIENT_ID}\",\"apiKey\": \"${API_KEY}\",
              \"scope\": \"https://www.googleapis.com/auth/calendar\",\"discoveryDocs\": [\"https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest\"]}'' 
              > ./apiGoogleconfig.json 
        stage: Test
        script: 
          - cd test/react
          - npm run test
